// <auto-generated />
namespace RentalMovies.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMin18YearsValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMin18YearsValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201124182_AddMin18YearsValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
