// <auto-generated />
namespace RentalMovies.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newMovieAttribute_and_addGenreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMovieAttribute_and_addGenreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201056115_newMovieAttribute_and_addGenreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
