// <auto-generated />
namespace RentalMovies.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class POPULATEMembershipType1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(POPULATEMembershipType1));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201114576_POPULATEMembershipType1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
